// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: type/v1/sample_basic_message.proto

// 공용으로 사용하는 메세지들을 정의하는 패키지

package typev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 어느 서비스에서 요청한 API인지를 정의하는 enum
// Unspecified request
// Request from Debug API
// Request from Open API
type RequestNode int32

const (
	RequestNode_REQUEST_NODE_UNSPECIFIED RequestNode = 0
	RequestNode_REQUEST_NODE_DEBUG_API   RequestNode = 1
	RequestNode_REQUEST_NODE_OPEN_API    RequestNode = 2
	// Request from Web Application
	RequestNode_REQUEST_NODE_WEB_FRONT RequestNode = 3
	// Request from Service 1
	RequestNode_REQUEST_NODE_ONE RequestNode = 4
	// Request from Service 2
	RequestNode_REQUEST_NODE_TWO RequestNode = 5
	// Request from Service 3
	RequestNode_REQUEST_NODE_THREE RequestNode = 6
	// Request from Custom interface
	RequestNode_REQUEST_NODE_CUSTOM RequestNode = 7
)

// Enum value maps for RequestNode.
var (
	RequestNode_name = map[int32]string{
		0: "REQUEST_NODE_UNSPECIFIED",
		1: "REQUEST_NODE_DEBUG_API",
		2: "REQUEST_NODE_OPEN_API",
		3: "REQUEST_NODE_WEB_FRONT",
		4: "REQUEST_NODE_ONE",
		5: "REQUEST_NODE_TWO",
		6: "REQUEST_NODE_THREE",
		7: "REQUEST_NODE_CUSTOM",
	}
	RequestNode_value = map[string]int32{
		"REQUEST_NODE_UNSPECIFIED": 0,
		"REQUEST_NODE_DEBUG_API":   1,
		"REQUEST_NODE_OPEN_API":    2,
		"REQUEST_NODE_WEB_FRONT":   3,
		"REQUEST_NODE_ONE":         4,
		"REQUEST_NODE_TWO":         5,
		"REQUEST_NODE_THREE":       6,
		"REQUEST_NODE_CUSTOM":      7,
	}
)

func (x RequestNode) Enum() *RequestNode {
	p := new(RequestNode)
	*p = x
	return p
}

func (x RequestNode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestNode) Descriptor() protoreflect.EnumDescriptor {
	return file_type_v1_sample_basic_message_proto_enumTypes[0].Descriptor()
}

func (RequestNode) Type() protoreflect.EnumType {
	return &file_type_v1_sample_basic_message_proto_enumTypes[0]
}

func (x RequestNode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestNode.Descriptor instead.
func (RequestNode) EnumDescriptor() ([]byte, []int) {
	return file_type_v1_sample_basic_message_proto_rawDescGZIP(), []int{0}
}

// Request, Response에서 공용으로 사용하는 Header
// Service Version
type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ToIds   []string `protobuf:"bytes,2,rep,name=to_ids,json=toIds,proto3" json:"to_ids,omitempty"`
	// Requester
	FromId RequestNode `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3,enum=type.v1.RequestNode" json:"from_id,omitempty"`
	// User Web ClientID
	RequesterId string `protobuf:"bytes,4,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_type_v1_sample_basic_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_type_v1_sample_basic_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_type_v1_sample_basic_message_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Header) GetToIds() []string {
	if x != nil {
		return x.ToIds
	}
	return nil
}

func (x *Header) GetFromId() RequestNode {
	if x != nil {
		return x.FromId
	}
	return RequestNode_REQUEST_NODE_UNSPECIFIED
}

func (x *Header) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

// Body없이 Header만 포함
type WithoutBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // Standard
	Error  *Error  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *WithoutBody) Reset() {
	*x = WithoutBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_type_v1_sample_basic_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithoutBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithoutBody) ProtoMessage() {}

func (x *WithoutBody) ProtoReflect() protoreflect.Message {
	mi := &file_type_v1_sample_basic_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithoutBody.ProtoReflect.Descriptor instead.
func (*WithoutBody) Descriptor() ([]byte, []int) {
	return file_type_v1_sample_basic_message_proto_rawDescGZIP(), []int{1}
}

func (x *WithoutBody) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WithoutBody) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Standard Error Message
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                             // Fail : -1, Success : 0, Delay : 1
	Code        int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                                 // Error Code
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                  // Error Name
	Reason      string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                              // Error Message
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                    // Error Description
	ServiceName string `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Service Name
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_type_v1_sample_basic_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_type_v1_sample_basic_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_type_v1_sample_basic_message_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Error) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_type_v1_sample_basic_message_proto protoreflect.FileDescriptor

var file_type_v1_sample_basic_message_proto_rawDesc = []byte{
	0x0a, 0x22, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x5f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x8b, 0x01,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x49, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x0b, 0x57,
	0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa4, 0x01, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x2a, 0xdb, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x18, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x44, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a,
	0x0a, 0x16, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x44,
	0x45, 0x42, 0x55, 0x47, 0x5f, 0x41, 0x50, 0x49, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x5f,
	0x41, 0x50, 0x49, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x57, 0x45, 0x42, 0x5f, 0x46, 0x52, 0x4f, 0x4e, 0x54, 0x10,
	0x03, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x44,
	0x45, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x57, 0x4f, 0x10, 0x05, 0x12, 0x16, 0x0a,
	0x12, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x48,
	0x52, 0x45, 0x45, 0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x10, 0x07, 0x42, 0x76,
	0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x17, 0x53,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x11, 0x70, 0x62, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x54, 0x58,
	0x58, 0xaa, 0x02, 0x07, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x07, 0x54, 0x79,
	0x70, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x13, 0x54, 0x79, 0x70, 0x65, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x54, 0x79,
	0x70, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_type_v1_sample_basic_message_proto_rawDescOnce sync.Once
	file_type_v1_sample_basic_message_proto_rawDescData = file_type_v1_sample_basic_message_proto_rawDesc
)

func file_type_v1_sample_basic_message_proto_rawDescGZIP() []byte {
	file_type_v1_sample_basic_message_proto_rawDescOnce.Do(func() {
		file_type_v1_sample_basic_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_type_v1_sample_basic_message_proto_rawDescData)
	})
	return file_type_v1_sample_basic_message_proto_rawDescData
}

var file_type_v1_sample_basic_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_type_v1_sample_basic_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_type_v1_sample_basic_message_proto_goTypes = []interface{}{
	(RequestNode)(0),    // 0: type.v1.RequestNode
	(*Header)(nil),      // 1: type.v1.Header
	(*WithoutBody)(nil), // 2: type.v1.WithoutBody
	(*Error)(nil),       // 3: type.v1.Error
}
var file_type_v1_sample_basic_message_proto_depIdxs = []int32{
	0, // 0: type.v1.Header.from_id:type_name -> type.v1.RequestNode
	1, // 1: type.v1.WithoutBody.header:type_name -> type.v1.Header
	3, // 2: type.v1.WithoutBody.error:type_name -> type.v1.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_type_v1_sample_basic_message_proto_init() }
func file_type_v1_sample_basic_message_proto_init() {
	if File_type_v1_sample_basic_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_type_v1_sample_basic_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_type_v1_sample_basic_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithoutBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_type_v1_sample_basic_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_type_v1_sample_basic_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_type_v1_sample_basic_message_proto_goTypes,
		DependencyIndexes: file_type_v1_sample_basic_message_proto_depIdxs,
		EnumInfos:         file_type_v1_sample_basic_message_proto_enumTypes,
		MessageInfos:      file_type_v1_sample_basic_message_proto_msgTypes,
	}.Build()
	File_type_v1_sample_basic_message_proto = out.File
	file_type_v1_sample_basic_message_proto_rawDesc = nil
	file_type_v1_sample_basic_message_proto_goTypes = nil
	file_type_v1_sample_basic_message_proto_depIdxs = nil
}
